# Generated by Django 4.0 on 2022-01-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='payement_recieved',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Payment Recieved'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='delivery',
            field=models.CharField(blank=True, default=None, max_length=20, verbose_name='Destination'),
        ),
    ]
