# Generated by Django 4.0 on 2022-01-13 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_party_payement_recieved_alter_invoice_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='payement_recieved',
            new_name='payment_recieved',
        ),
    ]
